// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace VDFinVoucherTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("check VdFin Vocher")]
    public partial class CheckVdFinVocherFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Vdf-voucher.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "check VdFin Vocher", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Go to brand form page and download pdf")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void GoToBrandFormPageAndDownloadPdf()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Go to brand form page and download pdf", new string[] {
                        "mytag"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/fr/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.When("I press print button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("PDF should be downloaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#81429 check FR text in homepage")]
        public virtual void _81429CheckFRTextInHomepage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81429 check FR text in homepage", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
 testRunner.When("The home page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "line",
                        "text"});
            table1.AddRow(new string[] {
                        "li",
                        "Bienvenue"});
            table1.AddRow(new string[] {
                        "span",
                        "Choisissez votre langue"});
#line 14
 testRunner.Then("I should see the text in homepage", ((string)(null)), table1, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#81429 check FR text in landing page")]
        public virtual void _81429CheckFRTextInLandingPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81429 check FR text in landing page", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/fr/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 21
 testRunner.When("The landing page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "line",
                        "text"});
            table2.AddRow(new string[] {
                        "h1",
                        "Le moment est venu d’envisager quelque chose de nouveau"});
            table2.AddRow(new string[] {
                        "p",
                        "Vous avez certainement vécu des moments très agréables ces dernières années au vo" +
                            "lant de votre voiture. Mais le temps file et votre contrat de financement arrive" +
                            " bientôt à échéance. Savez-vous déjà quel sera votre prochain coup de cœur ?"});
            table2.AddRow(new string[] {
                        "//p[2]",
                        @"Votre distributeur a d’excellentes nouvelles pour vous\r
 Comme mentionné dans la lettre que vous avez reçue dernièrement, nous tenons à récompenser votre fidélité. Entrez votre identifiant ci-dessous, téléchargez votre voucher de fidélité et remettez-le à votre distributeur. Il vous fera une offre sur mesure à un tarif « fidélité » très avantageux. Vous allez être agréablement surpris(e) !"});
            table2.AddRow(new string[] {
                        "//p[3]",
                        "Profitez-en sans attendre. Identifiez-vous !"});
            table2.AddRow(new string[] {
                        "label",
                        "Votre identifiant :?"});
            table2.AddRow(new string[] {
                        "input.submit-button",
                        "POURSUIVRE"});
#line 22
 testRunner.Then("I should see the text in landing page", ((string)(null)), table2, "Then ");
#line 30
 testRunner.And("I click help button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "line",
                        "text"});
            table3.AddRow(new string[] {
                        "h2",
                        "Où trouver mon identifiant ?"});
            table3.AddRow(new string[] {
                        "div.content-wrapper > p",
                        "Votre identifiant personnel est repris dans le courrier envoyé par la poste à vot" +
                            "re domicile. Vous ne le retrouvez plus ? Pas de soucis ! Votre identifiant corre" +
                            "spond au numéro de votre contrat de financement actuel chez Volkswagen D’Ieteren" +
                            " Finance."});
#line 31
 testRunner.And("I should see the text in help pop-up", ((string)(null)), table3, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#81429 check NL text in homepage")]
        public virtual void _81429CheckNLTextInHomepage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81429 check NL text in homepage", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line 37
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
 testRunner.When("The home page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "line",
                        "text"});
            table4.AddRow(new string[] {
                        "//li[2]",
                        "Welkom"});
            table4.AddRow(new string[] {
                        "//span[2]",
                        "Kies uw taal"});
#line 39
 testRunner.Then("I should see the text in homepage", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#81429 check NL text in landing page")]
        public virtual void _81429CheckNLTextInLandingPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81429 check NL text in landing page", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/nl/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 46
 testRunner.When("The landing page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "line",
                        "text"});
            table5.AddRow(new string[] {
                        "h1",
                        "Dit is het perfecte moment om naar iets nieuws uit te kijken"});
            table5.AddRow(new string[] {
                        "p",
                        "De voorbije jaren heeft u ongetwijfeld veel rijplezier beleefd aan uw wagen. Uw f" +
                            "inancieringscontract loopt echter binnenkort af. Inderdaad, de tijd gaat snel. H" +
                            "eeft u al nagedacht over uw toekomstige keuze?"});
            table5.AddRow(new string[] {
                        "//p[2]",
                        @"Uw verdeler heeft goed nieuws voor u\r
 Zoals vermeld in de brief die u reeds heeft ontvangen, belonen wij uw trouw! Voer uw login hieronder in, download uw getrouwheidsvoucher en ga ermee naar uw verdeler. Uw verdeler zal u een offerte op maat maken aan een interessant getrouwheidstarief. U mag een onweerstaanbaar aanbod verwachten!"});
            table5.AddRow(new string[] {
                        "//p[3]",
                        "Log meteen in en profiteer ervan!"});
            table5.AddRow(new string[] {
                        "label",
                        "Uw login:?"});
            table5.AddRow(new string[] {
                        "input.submit-button",
                        "VERDER"});
#line 47
 testRunner.Then("I should see the text in landing page", ((string)(null)), table5, "Then ");
#line 55
 testRunner.And("I click help button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "line",
                        "text"});
            table6.AddRow(new string[] {
                        "h2",
                        "Waar vind ik mijn login?"});
            table6.AddRow(new string[] {
                        "div.content-wrapper > p",
                        "Uw persoonlijke login staat vermeld in de brief die u via de post heeft ontvangen" +
                            ". Bent u deze brief kwijt? Geen probleem. Uw login is het contractnummer van uw " +
                            "huidig financieringscontract bij Volkswagen D’Ieteren Finance."});
#line 56
 testRunner.And("I should see the text in help pop-up", ((string)(null)), table6, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82358 check blue box in FR")]
        public virtual void _82358CheckBlueBoxInFR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82358 check blue box in FR", ((string[])(null)));
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/fr/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
 testRunner.When("The landing page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 64
 testRunner.Then("I shouldn\'t see the blue box \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82358 check blue box in NL")]
        public virtual void _82358CheckBlueBoxInNL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82358 check blue box in NL", ((string[])(null)));
#line 66
this.ScenarioSetup(scenarioInfo);
#line 67
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/nl/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
 testRunner.When("The landing page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 69
 testRunner.Then("I shouldn\'t see the blue box \"NL\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82365 check bullet with i FR")]
        public virtual void _82365CheckBulletWithIFR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82365 check bullet with i FR", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/fr/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 73
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.When("The home page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 76
 testRunner.Then("I shouldn\'t see the bullet \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82365 check bullet with i NL")]
        public virtual void _82365CheckBulletWithINL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82365 check bullet with i NL", ((string[])(null)));
#line 78
this.ScenarioSetup(scenarioInfo);
#line 79
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/nl/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 80
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.When("The home page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 83
 testRunner.Then("I shouldn\'t see the bullet \"NL\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82382 check email field FR")]
        public virtual void _82382CheckEmailFieldFR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82382 check email field FR", ((string[])(null)));
#line 85
this.ScenarioSetup(scenarioInfo);
#line 86
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/fr/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 87
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 88
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 90
 testRunner.Then("I should see the email field is filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82382 check email field NL")]
        public virtual void _82382CheckEmailFieldNL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82382 check email field NL", ((string[])(null)));
#line 92
this.ScenarioSetup(scenarioInfo);
#line 93
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/nl/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 94
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 95
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 97
 testRunner.Then("I should see the email field is filled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82385 check \"next\" translation FR")]
        public virtual void _82385CheckNextTranslationFR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82385 check \"next\" translation FR", ((string[])(null)));
#line 99
this.ScenarioSetup(scenarioInfo);
#line 100
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/fr/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 101
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 104
 testRunner.Then("I should see \"Suivant\" in next button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82385 check \"next\" translation NL")]
        public virtual void _82385CheckNextTranslationNL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82385 check \"next\" translation NL", ((string[])(null)));
#line 106
this.ScenarioSetup(scenarioInfo);
#line 107
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/nl/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 108
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 111
 testRunner.Then("I should see \"Volgende\" in next button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82386 check email label FR")]
        public virtual void _82386CheckEmailLabelFR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82386 check email label FR", ((string[])(null)));
#line 113
this.ScenarioSetup(scenarioInfo);
#line 114
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/fr/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 115
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 116
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 118
 testRunner.Then("I shouldn\'t see email text twice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82386 check email label NL")]
        public virtual void _82386CheckEmailLabelNL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82386 check email label NL", ((string[])(null)));
#line 120
this.ScenarioSetup(scenarioInfo);
#line 121
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/nl/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 122
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 125
 testRunner.Then("I shouldn\'t see email text twice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82401 check \"next\" translation NL")]
        public virtual void _82401CheckNextTranslationNL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82401 check \"next\" translation NL", ((string[])(null)));
#line 127
this.ScenarioSetup(scenarioInfo);
#line 128
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/nl/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 129
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 132
 testRunner.Then("I the text in box should has been changed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82386 check address translations FR")]
        public virtual void _82386CheckAddressTranslationsFR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82386 check address translations FR", ((string[])(null)));
#line 134
this.ScenarioSetup(scenarioInfo);
#line 135
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/fr/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 136
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 137
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 138
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 139
 testRunner.Then("I should see address has changed \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82386 check address translations NL")]
        public virtual void _82386CheckAddressTranslationsNL()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82386 check address translations NL", ((string[])(null)));
#line 141
this.ScenarioSetup(scenarioInfo);
#line 142
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/nl/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 143
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 144
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 145
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 146
 testRunner.Then("I should see address has changed \"NL\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("#82409 check label translations in box FR")]
        public virtual void _82409CheckLabelTranslationsInBoxFR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82409 check label translations in box FR", ((string[])(null)));
#line 148
this.ScenarioSetup(scenarioInfo);
#line 149
 testRunner.Given("I navigate to the page \"http://vdf-voucher.t1.voxteneo.com/fr/Home/CheckContractN" +
                    "umber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 150
 testRunner.And("I input contract number field with \"123-1234562-AU\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
 testRunner.And("I press submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 152
 testRunner.When("I press email button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 153
 testRunner.Then("I should see the label translation has been changed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
