// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AstralTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class AstralAdminFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AstralAdmin.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AstralAdmin", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "AstralAdmin")))
            {
                AstralTest.AstralAdminFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#82642 check create new vehicle type")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void _82642CheckCreateNewVehicleType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82642 check create new vehicle type", new string[] {
                        "mytag"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table1.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 5
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table1, "Given ");
#line 8
 testRunner.When("I input the Vehicle type name \"Van\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.And("I press \"Create\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.Then("I should see the alert success message \"Vehicle Type successfully added.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#82642 check create new vehicle type(that already exist)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _82642CheckCreateNewVehicleTypeThatAlreadyExist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82642 check create new vehicle type(that already exist)", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table2.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 13
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table2, "Given ");
#line 16
 testRunner.When("I input the Vehicle type name \"Van\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.And("I press \"Create\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.Then("I should see the alert error message \"Same entry has been found. Please use anoth" +
                    "er Name-en\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#82642 check create new vehicle type(is empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _82642CheckCreateNewVehicleTypeIsEmpty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#82642 check create new vehicle type(is empty)", ((string[])(null)));
#line 20
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table3.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 21
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table3, "Given ");
#line 24
 testRunner.When("I input the Vehicle type name \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
 testRunner.And("I press \"Create\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.Then("I should see the error message \"Name\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#92319 Going to Edit Driver")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _92319GoingToEditDriver()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#92319 Going to Edit Driver", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table4.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 29
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table4, "Given ");
#line 32
 testRunner.And("I go to Costumer Edit page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.When("I click \"Drivers\" tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#92319 Successfully Edit Driver")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _92319SuccessfullyEditDriver()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#92319 Successfully Edit Driver", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table5.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 36
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table5, "Given ");
#line 39
 testRunner.And("I go to Costumer Edit page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I click \"Drivers\" tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("I click edit icon on driver tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.When("I input driver name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.When("I click save button \"modalDriverSave\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
 testRunner.Then("I should able to see message \"Driver is successfully updated.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#92319 Failed to Edit Driver with blank field")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _92319FailedToEditDriverWithBlankField()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#92319 Failed to Edit Driver with blank field", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table6.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 47
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table6, "Given ");
#line 50
 testRunner.And("I go to Costumer Edit page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.And("I click \"Drivers\" tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.And("I click edit icon on driver tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.And("I delete all data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
 testRunner.When("I click save button \"modalDriverSave\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 55
 testRunner.Then("I should able to see the error message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#92319 Failed to Edit Driver with age under 18 years old")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _92319FailedToEditDriverWithAgeUnder18YearsOld()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#92319 Failed to Edit Driver with age under 18 years old", ((string[])(null)));
#line 57
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table7.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 58
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table7, "Given ");
#line 61
 testRunner.And("I go to Costumer Edit page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.And("I click \"Drivers\" tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.And("I click edit icon on driver tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("I input the birth date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.When("I click save button \"modalDriverSave\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
 testRunner.Then("I should able to see the error message on brithdate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#92319 Cancel to Edit Driver")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _92319CancelToEditDriver()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#92319 Cancel to Edit Driver", ((string[])(null)));
#line 68
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table8.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 69
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table8, "Given ");
#line 72
 testRunner.And("I go to Costumer Edit page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 73
 testRunner.And("I click \"Drivers\" tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And("I click edit icon on driver tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.When("I click close button on edit driver pop-up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#91755 filter by contact person surename")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _91755FilterByContactPersonSurename()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#91755 filter by contact person surename", ((string[])(null)));
#line 77
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table9.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 78
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table9, "Given ");
#line 81
 testRunner.And("I go to Customer list page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.And("I open filter form", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.When("I input name with \"Basiah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 84
 testRunner.And("I press search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.Then("I should see the customer with surename \"Basiah\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#92055 check create new vehicle type")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _92055CheckCreateNewVehicleType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#92055 check create new vehicle type", ((string[])(null)));
#line 87
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table10.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 88
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table10, "Given ");
#line 91
 testRunner.And("I go to Vehicle Edit page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.And("I click \"Plate\" tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 93
 testRunner.And("I click create new button on plate tab", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "plateNumber",
                        "startDate",
                        "endDate"});
            table11.AddRow(new string[] {
                        "Y6GT",
                        "18/11/2016",
                        "20/11/2016"});
#line 94
 testRunner.When("I input plate data", ((string)(null)), table11, "When ");
#line 97
 testRunner.And("I click save button \"savePlateNumber\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 98
 testRunner.Then("I should able to see message \"Vehicle plate number successfully created.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#91473 check document/email template data on page 2")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _91473CheckDocumentEmailTemplateDataOnPage2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#91473 check document/email template data on page 2", ((string[])(null)));
#line 100
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table12.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 101
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table12, "Given ");
#line 104
 testRunner.And("I go to document/email template page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.When("I go to page \"2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 106
 testRunner.Then("I should see \"2\" data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#89386 check delete translation")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _89386CheckDeleteTranslation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#89386 check delete translation", ((string[])(null)));
#line 108
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table13.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 109
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table13, "Given ");
#line 112
 testRunner.And("I go to document/email template edit page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 113
 testRunner.When("I click delete icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
 testRunner.And("I click save button on document/email template page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
 testRunner.Then("I should able to see message \"Template has been saved\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#97399 check Weird label in planning page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _97399CheckWeirdLabelInPlanningPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#97399 check Weird label in planning page", ((string[])(null)));
#line 117
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table14.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 118
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table14, "Given ");
#line 121
 testRunner.When("I press \"Planning\" menu on side bar menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 122
 testRunner.And("I change language to \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "xpath",
                        "translation"});
            table15.AddRow(new string[] {
                        "//div[2]/div/button",
                        "Réduire tout"});
            table15.AddRow(new string[] {
                        "//div[2]/div/button[2]",
                        "Développer tout"});
            table15.AddRow(new string[] {
                        "//div[2]/button",
                        "journée"});
#line 123
 testRunner.Then("I should see correct translation", ((string)(null)), table15, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#96945 check label translation on customer group page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _96945CheckLabelTranslationOnCustomerGroupPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#96945 check label translation on customer group page", ((string[])(null)));
#line 129
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table16.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 130
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table16, "Given ");
#line 133
 testRunner.When("I change language to \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 134
 testRunner.And("I go to customer group page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "xpath",
                        "translation"});
            table17.AddRow(new string[] {
                        "//h1",
                        "GROUPE DE CLIENTS"});
            table17.AddRow(new string[] {
                        "//th/div/span",
                        "Nom"});
            table17.AddRow(new string[] {
                        "//th[2]/div/span",
                        "Action fr"});
#line 135
 testRunner.Then("I should see correct translation", ((string)(null)), table17, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#96945 check label translation on create customer group page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _96945CheckLabelTranslationOnCreateCustomerGroupPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#96945 check label translation on create customer group page", ((string[])(null)));
#line 141
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table18.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 142
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table18, "Given ");
#line 145
 testRunner.When("I change language to \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 146
 testRunner.And("I go to customer group page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 147
 testRunner.And("I press \"Add New fr\" menu on side bar menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "xpath",
                        "translation"});
            table19.AddRow(new string[] {
                        "//h1",
                        "GROUPE DE CLIENTS"});
            table19.AddRow(new string[] {
                        "//label",
                        "Nom *"});
#line 148
 testRunner.Then("I should see correct translation", ((string)(null)), table19, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#96945 check label translation on blocking setting page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _96945CheckLabelTranslationOnBlockingSettingPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#96945 check label translation on blocking setting page", ((string[])(null)));
#line 153
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table20.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 154
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table20, "Given ");
#line 157
 testRunner.When("I change language to \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 158
 testRunner.And("I press \"Client\" menu on side bar menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 159
 testRunner.And("I press \"Paramètres de blocage\" menu on side bar menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 160
 testRunner.And("I press \"Créer un nouveau\" menu on side bar menu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "xpath",
                        "translation"});
            table21.AddRow(new string[] {
                        "//th[3]",
                        "Action fr"});
#line 161
 testRunner.Then("I should see correct translation", ((string)(null)), table21, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#96945 check label translation on customer page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _96945CheckLabelTranslationOnCustomerPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#96945 check label translation on customer page", ((string[])(null)));
#line 165
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table22.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 166
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table22, "Given ");
#line 169
 testRunner.When("I change language to \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 170
 testRunner.And("I go to customer page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "xpath",
                        "translation"});
            table23.AddRow(new string[] {
                        "//th/div/span",
                        "Nom"});
            table23.AddRow(new string[] {
                        "//th[2]/div/span",
                        "Type de client"});
            table23.AddRow(new string[] {
                        "//th[3]/div/span",
                        "Groupe de clients"});
            table23.AddRow(new string[] {
                        "//th[4]/div/span",
                        "Adresse"});
            table23.AddRow(new string[] {
                        "//th[5]/div/span",
                        "Téléphone"});
            table23.AddRow(new string[] {
                        "//th[6]/div/span",
                        "GSM"});
            table23.AddRow(new string[] {
                        "//th[7]/div/span",
                        "Email"});
            table23.AddRow(new string[] {
                        "//th[8]/div/span",
                        "Action fr"});
            table23.AddRow(new string[] {
                        "//form/button",
                        "Exportation"});
            table23.AddRow(new string[] {
                        "//div[2]/div/div/a",
                        "Ajouter un nouveau"});
#line 171
 testRunner.Then("I should see correct translation", ((string)(null)), table23, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#96945 check label translation on filter customer page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _96945CheckLabelTranslationOnFilterCustomerPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#96945 check label translation on filter customer page", ((string[])(null)));
#line 184
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table24.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 185
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table24, "Given ");
#line 188
 testRunner.When("I change language to \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 189
 testRunner.And("I go to customer page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 190
 testRunner.And("I press filter icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "xpath",
                        "translation"});
            table25.AddRow(new string[] {
                        "//option",
                        "Tous les types de clients"});
            table25.AddRow(new string[] {
                        "//div[3]/div/select/option",
                        "Tous les groupes clients"});
            table25.AddRow(new string[] {
                        "//div[2]/div[3]/label",
                        "Email"});
#line 191
 testRunner.Then("I should see correct translation", ((string)(null)), table25, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#96945 check label translation on vehicle page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "AstralAdmin")]
        public virtual void _96945CheckLabelTranslationOnVehiclePage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#96945 check label translation on vehicle page", ((string[])(null)));
#line 197
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table26.AddRow(new string[] {
                        "Admin",
                        "_Admin1!"});
#line 198
 testRunner.Given("I loggin to the website as admin", ((string)(null)), table26, "Given ");
#line 201
 testRunner.When("I change language to \"FR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 202
 testRunner.And("I go to vehicle page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "xpath",
                        "translation"});
            table27.AddRow(new string[] {
                        "//div[2]/div/a",
                        "FILTER YOUR RESULT FR"});
            table27.AddRow(new string[] {
                        "//th[10]/div/span",
                        "Action fr"});
#line 203
 testRunner.Then("I should see correct translation", ((string)(null)), table27, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
