// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace EHSTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class TestAdminT1Feature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "testAdmint1.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "test Admin t1", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "test Admin t1")))
            {
                EHSTest.TestAdminT1Feature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("verify add news form by admin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("mytag")]
        public virtual void VerifyAddNewsFormByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify add news form by admin", new string[] {
                        "mytag"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table1.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 5
 testRunner.Given("I login to ehs website", ((string)(null)), table1, "Given ");
#line 8
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.And("the Manage News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When("I click \"Add new\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("the Add News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("verify success add news by admin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void VerifySuccessAddNewsByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify success add news by admin", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table2.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 14
 testRunner.Given("I login to ehs website", ((string)(null)), table2, "Given ");
#line 17
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("the Add News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.When("I upload the image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "imageTitle",
                        "newsTitle",
                        "shortDescription",
                        "newsContent"});
            table3.AddRow(new string[] {
                        "test image title",
                        "test news title",
                        "test short description",
                        "test news content"});
#line 20
 testRunner.And("I input the add news form", ((string)(null)), table3, "And ");
#line 23
 testRunner.And("I click publish button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.Then("I should see pop-up notification \"Add news successfully!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("verify failed add news by admin(the required field is empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void VerifyFailedAddNewsByAdminTheRequiredFieldIsEmpty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify failed add news by admin(the required field is empty)", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table4.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 27
 testRunner.Given("I login to ehs website", ((string)(null)), table4, "Given ");
#line 30
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.And("the Add News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.When("I click publish button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
 testRunner.Then("I should see a error message \"news\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("verify success save to draft news by admin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void VerifySuccessSaveToDraftNewsByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify success save to draft news by admin", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table5.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 36
 testRunner.Given("I login to ehs website", ((string)(null)), table5, "Given ");
#line 39
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("the Add News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.When("I upload the image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "imageTitle",
                        "newsTitle",
                        "shortDescription",
                        "newsContent"});
            table6.AddRow(new string[] {
                        "test image title",
                        "test news title",
                        "test short description",
                        "test news content"});
#line 42
 testRunner.And("I input the add news form", ((string)(null)), table6, "And ");
#line 45
 testRunner.And("I click save to draft button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.Then("I should see pop-up notification \"Add news successfully!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Verify manage news page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void VerifyManageNewsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Verify manage news page", ((string[])(null)));
#line 48
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table7.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 49
 testRunner.Given("I login to ehs website", ((string)(null)), table7, "Given ");
#line 52
 testRunner.And("I go to manage news page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.When("the manage news page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.Then("I check Add new button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 55
 testRunner.And("I check search function", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("I check filtering by language", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("I check filtering by show entries \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.And("I check filtering by show entries \"5\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 59
 testRunner.And("I check sorting the data table", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("I check view on public site", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And("I check Edit News \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.And("I check Delete News \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
 testRunner.And("I check see all translation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("verify success edit news by admin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void VerifySuccessEditNewsByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("verify success edit news by admin", ((string[])(null)));
#line 65
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table8.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 66
 testRunner.Given("I login to ehs website", ((string)(null)), table8, "Given ");
#line 69
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And("the Manage News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.When("I click edit icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "imageTitle",
                        "newsTitle",
                        "shortDescription"});
            table9.AddRow(new string[] {
                        "test image title change",
                        "test news title change",
                        "test short description change"});
#line 72
 testRunner.And("I input the edit news form", ((string)(null)), table9, "And ");
#line 75
 testRunner.And("I click publish button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.Then("I should see pop-up notification \"News saved successfully!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#74673 verify success add page by admin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _74673VerifySuccessAddPageByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#74673 verify success add page by admin", ((string[])(null)));
#line 78
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table10.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 79
 testRunner.Given("I login to ehs website", ((string)(null)), table10, "Given ");
#line 82
 testRunner.And("I am on manage page admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/p" +
                    "age/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
 testRunner.And("the Add Pages page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.When("I upload the image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "metaDescription",
                        "metaKeyWords",
                        "title",
                        "url",
                        "content"});
            table11.AddRow(new string[] {
                        "test description",
                        "testKeyswords",
                        "test title",
                        "test-title",
                        "test content"});
#line 85
 testRunner.And("I input the add page form", ((string)(null)), table11, "And ");
#line 88
 testRunner.And("I click publish button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.Then("I should see pop-up notification \"Add page successfully!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#74673 verify failed add page by admin(the required field is empty)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _74673VerifyFailedAddPageByAdminTheRequiredFieldIsEmpty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#74673 verify failed add page by admin(the required field is empty)", ((string[])(null)));
#line 91
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table12.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 92
 testRunner.Given("I login to ehs website", ((string)(null)), table12, "Given ");
#line 95
 testRunner.And("I am on manage page admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/p" +
                    "age/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 96
 testRunner.And("the Add Pages page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.When("I click publish button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 98
 testRunner.Then("I should see a error message \"page\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#74673 verify success save to draft page by admin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _74673VerifySuccessSaveToDraftPageByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#74673 verify success save to draft page by admin", ((string[])(null)));
#line 100
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table13.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 101
 testRunner.Given("I login to ehs website", ((string)(null)), table13, "Given ");
#line 104
 testRunner.And("I am on manage page admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/p" +
                    "age/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
 testRunner.And("the Add Pages page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
 testRunner.When("I upload the image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "metaDescription",
                        "metaKeyWords",
                        "title",
                        "url",
                        "content"});
            table14.AddRow(new string[] {
                        "test description1",
                        "testKeyswords1",
                        "test title1",
                        "test-title1",
                        "test content1"});
#line 107
 testRunner.And("I input the add page form", ((string)(null)), table14, "And ");
#line 110
 testRunner.And("I click save to draft button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 111
 testRunner.Then("I should see pop-up notification \"Add page successfully!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#73488 check view news of public when status is draft")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _73488CheckViewNewsOfPublicWhenStatusIsDraft()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#73488 check view news of public when status is draft", ((string[])(null)));
#line 113
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table15.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 114
 testRunner.Given("I login to ehs website", ((string)(null)), table15, "Given ");
#line 117
 testRunner.When("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 118
 testRunner.Then("the Manage News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#79019 check draft status")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _79019CheckDraftStatus()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#79019 check draft status", ((string[])(null)));
#line 120
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table16.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 121
 testRunner.Given("I login to ehs website", ((string)(null)), table16, "Given ");
#line 124
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
 testRunner.And("the Add News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
 testRunner.When("I upload the image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "imageTitle",
                        "newsTitle",
                        "shortDescription",
                        "newsContent"});
            table17.AddRow(new string[] {
                        "test image draft",
                        "test news draft12",
                        "test short draft",
                        "test news draft"});
#line 127
 testRunner.And("I input the add news form", ((string)(null)), table17, "And ");
#line 130
 testRunner.And("I click save to draft button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
 testRunner.Then("I input \"test news draft12\" to  search field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 132
 testRunner.And("I should see draft status on draft news", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#79019 check search by date")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _79019CheckSearchByDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#79019 check search by date", ((string[])(null)));
#line 134
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table18.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 135
 testRunner.Given("I login to ehs website", ((string)(null)), table18, "Given ");
#line 138
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
 testRunner.And("the Manage News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 140
 testRunner.When("I search data \"02/08/2016\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 141
 testRunner.Then("the search by date should be works", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#79019 check latest update news")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _79019CheckLatestUpdateNews()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#79019 check latest update news", ((string[])(null)));
#line 143
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table19.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 144
 testRunner.Given("I login to ehs website", ((string)(null)), table19, "Given ");
#line 147
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews/create\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 148
 testRunner.And("the Add News page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 149
 testRunner.When("I upload the image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "imageTitle",
                        "newsTitle",
                        "shortDescription",
                        "newsContent"});
            table20.AddRow(new string[] {
                        "test image title latest news",
                        "test latest news title",
                        "test short description latest news",
                        "test latest news content"});
#line 150
 testRunner.And("I input the add news form", ((string)(null)), table20, "And ");
#line 153
 testRunner.And("I click publish button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 154
 testRunner.And("I go to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 155
 testRunner.Then("I should see \"test latest news title\" as title in latest news", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#74677 verify success edit page by admin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _74677VerifySuccessEditPageByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#74677 verify success edit page by admin", ((string[])(null)));
#line 157
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table21.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 158
 testRunner.Given("I login to ehs website", ((string)(null)), table21, "Given ");
#line 161
 testRunner.And("I am on manage page admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/p" +
                    "age\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.And("the Manage Pages page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
 testRunner.When("I click edit icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 164
 testRunner.And("the edit page should be loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "title",
                        "content"});
            table22.AddRow(new string[] {
                        "change title",
                        "change content"});
#line 165
 testRunner.And("I input the edit pages form", ((string)(null)), table22, "And ");
#line 168
 testRunner.And("I upload the image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 169
 testRunner.And("I click publish button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 170
 testRunner.Then("I should see pop-up notification \"Page updated successfully!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#74676 verify success delete page by admin")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _74676VerifySuccessDeletePageByAdmin()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#74676 verify success delete page by admin", ((string[])(null)));
#line 172
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table23.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 173
 testRunner.Given("I login to ehs website", ((string)(null)), table23, "Given ");
#line 176
 testRunner.And("I am on manage page admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/p" +
                    "age\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 177
 testRunner.And("the Manage Pages page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 178
 testRunner.When("I click delete icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 179
 testRunner.And("the delete pop-up should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 180
 testRunner.And("I click yes button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 181
 testRunner.Then("I should see pop-up notification \"test title and related translations are deleted" +
                    "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#80805 check latest news")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _80805CheckLatestNews()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#80805 check latest news", ((string[])(null)));
#line 183
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table24.AddRow(new string[] {
                        "lucubanget",
                        "lucubanget"});
#line 184
 testRunner.Given("I login to ehs website", ((string)(null)), table24, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "imageTitle",
                        "newsTitle",
                        "shortDescription",
                        "newsContent"});
            table25.AddRow(new string[] {
                        "test first",
                        "test first",
                        "test first",
                        "test first"});
#line 187
 testRunner.When("I create news", ((string)(null)), table25, "When ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "imageTitle",
                        "newsTitle",
                        "shortDescription",
                        "newsContent"});
            table26.AddRow(new string[] {
                        "test latest",
                        "test latest",
                        "test latest",
                        "test latest"});
#line 190
 testRunner.And("I create news", ((string)(null)), table26, "And ");
#line 193
 testRunner.And("I go to home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 194
 testRunner.Then("I should see \"test latest\" as title in latest news", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#74672 check view page list")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _74672CheckViewPageList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#74672 check view page list", ((string[])(null)));
#line 196
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table27.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 197
 testRunner.Given("I login to ehs website", ((string)(null)), table27, "Given ");
#line 200
 testRunner.And("I am on manage page admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/p" +
                    "age\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 201
 testRunner.When("the Manage Pages page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 202
 testRunner.Then("I should see pagination", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 203
 testRunner.And("I should able to sort the list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 204
 testRunner.And("I shouldn\'t delete the default page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#74672 check view list of pages(not logged)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _74672CheckViewListOfPagesNotLogged()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#74672 check view list of pages(not logged)", ((string[])(null)));
#line 206
this.ScenarioSetup(scenarioInfo);
#line 207
 testRunner.Given("I open the driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 208
 testRunner.And("I am on manage page admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/p" +
                    "age\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 209
 testRunner.Then("I should see sign-in page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#73492 check view list of country")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _73492CheckViewListOfCountry()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#73492 check view list of country", ((string[])(null)));
#line 211
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table28.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 212
 testRunner.Given("I login to ehs website", ((string)(null)), table28, "Given ");
#line 215
 testRunner.And("I am on manage country page \"http://ehs.website-test.t1.voxteneo.com/#/admin/coun" +
                    "try\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 216
 testRunner.When("the Manage Country page is loaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 217
 testRunner.Then("I should see pagination", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 218
 testRunner.And("I filter by show entries", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 219
 testRunner.And("I sort by country name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 220
 testRunner.And("I should able to edit country", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#73492 check view list of country(not logged)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _73492CheckViewListOfCountryNotLogged()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#73492 check view list of country(not logged)", ((string[])(null)));
#line 222
this.ScenarioSetup(scenarioInfo);
#line 223
 testRunner.Given("I open the driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 224
 testRunner.And("I am on manage country page \"http://ehs.website-test.t1.voxteneo.com/#/admin/coun" +
                    "try\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
 testRunner.Then("I should see sign-in page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#74674 check view page on public")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _74674CheckViewPageOnPublic()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#74674 check view page on public", ((string[])(null)));
#line 227
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table29.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 228
 testRunner.Given("I login to ehs website", ((string)(null)), table29, "Given ");
#line 231
 testRunner.And("I am on manage page admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/p" +
                    "age\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 232
 testRunner.When("I click view on public icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 233
 testRunner.Then("the page should redirect to page on public", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#73489 check view news details")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _73489CheckViewNewsDetails()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#73489 check view news details", ((string[])(null)));
#line 235
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table30.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 236
 testRunner.Given("I login to ehs website", ((string)(null)), table30, "Given ");
#line 239
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 240
 testRunner.When("I click news title \"test news draft12\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 241
 testRunner.Then("the news detail content should read only", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 242
 testRunner.And("the page should redirect to edit page when edit button clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 243
 testRunner.And("the page should show delete pop-up when delete button clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#80776 check delete icon in manage news page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _80776CheckDeleteIconInManageNewsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#80776 check delete icon in manage news page", ((string[])(null)));
#line 245
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table31.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 246
 testRunner.Given("I login to ehs website", ((string)(null)), table31, "Given ");
#line 249
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 250
 testRunner.When("I click delete icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 251
 testRunner.Then("I should see delete news verification pop-up", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#80926 check search field in manage news")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _80926CheckSearchFieldInManageNews()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#80926 check search field in manage news", ((string[])(null)));
#line 253
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table32.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 254
 testRunner.Given("I login to ehs website", ((string)(null)), table32, "Given ");
#line 257
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 258
 testRunner.When("I search data \"test\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 259
 testRunner.And("I press enter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 260
 testRunner.Then("I should on manage news page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#81182 check create news localiztion")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _81182CheckCreateNewsLocaliztion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81182 check create news localiztion", ((string[])(null)));
#line 262
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table33.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 263
 testRunner.Given("I login to ehs website", ((string)(null)), table33, "Given ");
#line 266
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 267
 testRunner.When("I click \"Add new\" button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 268
 testRunner.Then("I should see the localization is \"http://ehs.website-test.t1.voxteneo.com/#/admin" +
                    "/news/create?lg=en\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#81182 check edit news localiztion")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _81182CheckEditNewsLocaliztion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81182 check edit news localiztion", ((string[])(null)));
#line 270
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table34.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 271
 testRunner.Given("I login to ehs website", ((string)(null)), table34, "Given ");
#line 274
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 275
 testRunner.When("I click edit icon", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 276
 testRunner.Then("I should see the localization is \"http://ehs.website-test.t1.voxteneo.com/#/admin" +
                    "/news/7/edit?lg=en\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#81182 check view news localiztion")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _81182CheckViewNewsLocaliztion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81182 check view news localiztion", ((string[])(null)));
#line 278
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table35.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 279
 testRunner.Given("I login to ehs website", ((string)(null)), table35, "Given ");
#line 282
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 283
 testRunner.When("I click news title \"test news draft12\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 284
 testRunner.Then("I should see the localization is \"http://ehs.website-test.t1.voxteneo.com/#/admin" +
                    "/news/7/view?lg=en\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#81182 check add news translation localiztion")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _81182CheckAddNewsTranslationLocaliztion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81182 check add news translation localiztion", ((string[])(null)));
#line 286
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table36.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 287
 testRunner.Given("I login to ehs website", ((string)(null)), table36, "Given ");
#line 290
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 291
 testRunner.When("I click \"see all translations\" link in admin page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 292
 testRunner.And("I click add icon traslation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 293
 testRunner.Then("I should see the localization is \"http://ehs.website-test.t1.voxteneo.com/#/admin" +
                    "/news/7/translate?source=en&target=fr\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#81240 check upload picture in manage country")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _81240CheckUploadPictureInManageCountry()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81240 check upload picture in manage country", ((string[])(null)));
#line 295
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table37.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 296
 testRunner.Given("I login to ehs website", ((string)(null)), table37, "Given ");
#line 299
 testRunner.And("I am on manage country page \"http://ehs.website-test.t1.voxteneo.com/#/admin/coun" +
                    "try\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 300
 testRunner.When("I click edit icon in manage country", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 301
 testRunner.And("I upload the image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 302
 testRunner.Then("the image should be uploaded", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#74675 check manage public content")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _74675CheckManagePublicContent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#74675 check manage public content", ((string[])(null)));
#line 304
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table38.AddRow(new string[] {
                        "EHSAdministrator",
                        "pass@word2016"});
#line 305
 testRunner.Given("I login to ehs website", ((string)(null)), table38, "Given ");
#line 308
 testRunner.And("I am on manage page admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/p" +
                    "age\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 309
 testRunner.When("I click news title \"Help\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 310
 testRunner.Then("I should see view detiail page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 311
 testRunner.And("all field should be read-only", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 312
 testRunner.And("edit and delete button should able to click", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("#81493 check field in view news detail page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "test Admin t1")]
        public virtual void _81493CheckFieldInViewNewsDetailPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("#81493 check field in view news detail page", ((string[])(null)));
#line 314
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                        "username",
                        "password"});
            table39.AddRow(new string[] {
                        "anggraeni",
                        "password"});
#line 315
 testRunner.Given("I login to ehs website", ((string)(null)), table39, "Given ");
#line 318
 testRunner.And("I am on manage news admin page \"http://ehs.website-test.t1.voxteneo.com/#/admin/n" +
                    "ews\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 319
 testRunner.When("I click news title \"test latest\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 320
 testRunner.Then("the news detail content should read only", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 321
 testRunner.And("the page should redirect to edit page when edit button clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 322
 testRunner.And("the page should show delete pop-up when delete button clicked", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
